language: node_js
node_js:
- '14'
script:
- echo '*****Build starting*****'
- echo 'Installing Dependencies'
- npm install
- echo 'Running tests'
- jest
env:
  global:
    secure: cSO+78g0xUHrYMIEjXbkkCEaUrikDnvjGs09wz9uGvx1TwmIPWEL8ie9HZfJ4DzwjOVggJA95ha/lpN8212um6uPo+QBIPi3JfhrQHMAzhzRlPu1TIE5u/262cb0rDw39a8d5Ui2TsVDGKA1xgYW8HjENHKax4/k/ODGTuG7Sw9hWyanlze1ozP9gfYTr8bp3fVyU5Zh13bz21h39/vHbR+Am4cnsoqA85mRmS8PrkNJdriGUQ7UlsNPuAdz4J1C0vQUDS8VHQoETEXAfLBGF1rzH8DAcZoyD2HtcwfyGYSJrYJgyOCZqq6J4MDVF+RX6k7XYH5VWKdd9nGEILFrSFkyrqPs3KzXn2oSI14sStxI6MRFkchlSUpgQkAZHpZ1XuvH8Gq8SBku2LrBbOqChYod8I+jrj/X5d2MVhNrVJ9Q7Ik3KNidgEUVcLmoEkUIgl0wlrL8j9lh73czQDxQDvr1K+36dIM2Z6wVAu6rI05yoNNF2ajVd8dTg9ospeMcNq9pZZAoJnzQQiGAVpzrQ40CsIIRfnPv0+IoK9Kf7ZxsREMD7nUaXfyMfUHgumG/izR7AO8VAKr3r3+8jgWRUJir5P2v3bA2nA6mFjtgGA6Sgzltny6TNZUhAeMSaW1sl04vPva+AtESF4ew2yVIBjtWpb/ofU+e3MSK2pHll8A=
